name: create-release-draft-with-op-file-on-tag-creation
run-name: Creating release draft for new tag ${{ github.ref_name }} triggered by ${{ github.actor }}

on:
  push:
    tags:
      - '**'

jobs:
  creating-release-draft-with-op-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: zip files into BetterCameraBindings.op
        run: zip -r -q BetterCameraBindings.op info.toml src
      - name: creating title for release draft
        id: release-draft-title
        run: echo "title=Better Camera Bindings $(echo ${{ github.ref_name }} | sed s/v//)" >> "$GITHUB_OUTPUT"
      - name: Create release draft with .op file
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.release-draft-title.outputs.title }}
          body: "## Changelog\n\n* INSERT CHANGES HERE"
          artifacts: BetterCameraBindings.op
          draft: true
          token: ${{ secrets.CREATE_RELEASE_DRAFT }}
